### ISSUE TITLE
Add MI estimators in R

### ISSUE THREAD

**Issue by pawel-czyz** [pawel-czyz/bmi#29]
As @a-marx told me, KSG, G-KSG, gKNN, and LNN are implemented in this [repository](https://github.com/a-marx/geodesic-mi). For the demo, look [here](https://github.com/a-marx/geodesic-mi/blob/master/code/experiments/run_test.R), at lines 97–113.

We can add it as a git submodule and plug it into our framework by creating an appropriate wrapper script in R. It it probably the best to parametrize it with [argparse](https://github.com/trevorld/r-argparse).

**Comment by a-marx** [comment]
LNN is implemented in the [rmi R package](https://cran.r-project.org/web/packages/rmi/index.html).
